// ISO-3166
export const COUNTRY_PARAMS_BY_ISO_CODE = {
  AT: {
    adminFileName: 'Austria_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  AL: {
    adminFileName: 'Albania_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  BY: {
    adminFileName: 'Belarus_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  BE: {
    adminFileName: 'Belgium_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  BA: {
    adminFileName: 'Bosnia_and_Herzegovina_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  BG: {
    adminFileName: 'Bulgaria_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  CA: {
    adminFileName: 'Canada_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_usacan.txt',
    subregions: {},
  },
  HR: {
    adminFileName: 'Croatia_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  CR: {
    adminFileName: 'Czech_Republic_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  DK: {
    adminFileName: 'Denmark_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  EE: {
    adminFileName: 'Estonia_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  FI: {
    adminFileName: 'Finland_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  FR: {
    adminFileName: 'France_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  DE: {
    adminFileName: 'Germany_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  GI: {
    adminFileName: 'Gibraltar_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  GR: {
    adminFileName: 'Greece_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  HU: {
    adminFileName: 'Hungary_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  IS: {
    adminFileName: 'Iceland_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  IR: {
    adminFileName: 'Ireland_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  IT: {
    adminFileName: 'Italy_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  LV: {
    adminFileName: 'Latvia_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  LT: {
    adminFileName: 'Lithuania_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  LU: {
    adminFileName: 'Luxembourg_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  MK: {
    adminFileName: 'Macedonia_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  MT: {
    adminFileName: 'Malta_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  MD: {
    adminFileName: 'Moldova_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  ME: {
    adminFileName: 'Montenegro_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  NL: {
    adminFileName: 'Netherlands_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  NO: {
    adminFileName: 'Norway_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  PT: {
    adminFileName: 'Portugal_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  PL: {
    adminFileName: 'Poland_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  RO: {
    adminFileName: 'Romania_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  RU: {
    adminFileName: 'Russia_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  RS: {
    adminFileName: 'Serbia_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  SK: {
    adminFileName: 'Slovakia_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  SI: {
    adminFileName: 'Slovenia_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  ES: {
    adminFileName: 'Spain_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  SE: {
    adminFileName: 'Sweden_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  CH: {
    adminFileName: 'Switzerland_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  UA: {
    adminFileName: 'Ukraine_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {},
  },
  GB: {
    adminFileName: 'United_Kingdom_admin.txt',
    preParamsFileName: 'preUK_R0=2.0.txt',
    populationDensityFileName: 'wpop_eur.txt',
    subregions: {
      'GB-LND': { name: 'London' },
    },
  },
  NG: {
    adminFileName: 'Nigeria_admin.txt',
    preParamsFileName: 'preNGA_R0=2.0.txt',
    populationDensityFileName: 'wpop_nga_adm1.txt',
    subregions: {},
  },
  US: {
    adminFileName: 'United_States_admin.txt',
    preParamsFileName: 'preUS_R0=2.0.txt',
    populationDensityFileName: 'wpop_usacan.txt',
    subregions: {
      // https://en.wikipedia.org/wiki/ISO_3166-2:US
      'US-AL': { name: 'Alabama' },
      'US-AK': {
        name: 'Alaska',
        adminFileName: 'Alaska_admin.txt',
        populationDensityFileName: 'wpop_us_terr.txt',
      },
      'US-AZ': { name: 'Arizona' },
      'US-AR': { name: 'Arkansas' },
      'US-CA': { name: 'California' },
      'US-CO': { name: 'Colorado' },
      'US-CT': { name: 'Connecticut' },
      'US-DE': { name: 'Delaware' },
      'US-FL': { name: 'Florida' },
      'US-GA': { name: 'Georgia' },
      'US-HI': {
        name: 'Hawaii',
        adminFileName: 'Hawaii_admin.txt',
        populationDensityFileName: 'wpop_us_terr.txt',
      },
      'US-ID': { name: 'Idaho' },
      'US-IL': { name: 'Illinois' },
      'US-IN': { name: 'Indiana' },
      'US-IA': { name: 'Iowa' },
      'US-KS': { name: 'Kansas' },
      'US-KY': { name: 'Kentucky' },
      'US-LA': { name: 'Louisiana' },
      'US-ME': { name: 'Maine' },
      'US-MD': { name: 'Maryland' },
      'US-MA': { name: 'Massachusetts' },
      'US-MI': { name: 'Michigan' },
      'US-MN': { name: 'Minnesota' },
      'US-MS': { name: 'Mississippi' },
      'US-MO': { name: 'Missouri' },
      'US-MT': { name: 'Montana' },
      'US-NE': { name: 'Nebraska' },
      'US-NV': { name: 'Nevada' },
      'US-NH': { name: 'New_Hampshire' },
      'US-NJ': { name: 'New_Jersey' },
      'US-NM': { name: 'New_Mexico' },
      'US-NY': { name: 'New_York' },
      'US-NC': { name: 'North_Carolina' },
      'US-ND': { name: 'North_Dakota' },
      'US-OH': { name: 'Ohio' },
      'US-OK': { name: 'Oklahoma' },
      'US-OR': { name: 'Oregon' },
      'US-PA': { name: 'Pennsylvania' },
      'US-RI': { name: 'Rhode_Island' },
      'US-SC': { name: 'South_Carolina' },
      'US-SD': { name: 'South_Dakota' },
      'US-TN': { name: 'Tennessee' },
      'US-TX': { name: 'Texas' },
      'US-UT': { name: 'Utah' },
      'US-VT': { name: 'Vermont' },
      'US-VA': { name: 'Virginia' },
      'US-WA': { name: 'Washington' },
      'US-WV': { name: 'West_Virginia' },
      'US-WI': { name: 'Wisconsin' },
      'US-WY': { name: 'Wyoming' },
      'US-DC': { name: 'District_of_Columbia' },
    },
  },
}
